### ISSUE TITLE
Arbitrary cap of 1000 iterations in hashmap_iterate

### ISSUE THREAD

**Issue by pseregiet** [Mashpoe/c-hashmap#3]
Function hashmap_iterate has a seemingly arbitrary cap on the number of loops set to 1000. Why ? Is there any reasons for that ? Seems like it was left accidentaly or something

``` 
void hashmap_iterate(hashmap* m, hashmap_callback c, void* user_ptr)
{
	// loop through the linked list of valid entries
	// this way we can skip over empty buckets
	struct bucket* current = m->first;
	
	int co = 0;

	while (current != NULL)
	{
		#ifdef __HASHMAP_REMOVABLE
		// "tombstone" check
		if (current->key != NULL)
		#endif
			c((void*)current->key, current->ksize, current->value, user_ptr);
		
		current = current->next;

		if (co > 1000)
		{
			break;
		}
		co++;

	}
}
```

**Comment by Mashpoe** [comment]
It looks like this was for debugging, and I forgot to remove it lol. The counter has been removed. Thanks for pointing this out! I'm surprised it took so long for this issue to be discovered.
